---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/drone-netlify
    tags: linux-amd64
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    password:
      from_secret: docker_password
    repo: techknowlogick/drone-netlify
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master
  - main

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/drone-netlify
    tags: linux-arm64
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    password:
      from_secret: docker_password
    repo: techknowlogick/drone-netlify
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master
  - main

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  pull: always
  image: plugins/docker:linux-arm
  settings:
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/drone-netlify
    tags: linux-arm
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    password:
      from_secret: docker_password
    repo: techknowlogick/drone-netlify
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master
  - main

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  branch:
  - master
  - main
  event:
  - push
  - tag

depends_on:
- linux-amd64
- linux-arm64
- linux-arm

...
